name: Publish
on:
  - workflow_dispatch


concurrency:
  group: "publish"
  cancel-in-progress: false


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Gradle Assemble
        run: ./gradlew assemble --info -S --show-version

  check:
    name: Check
    strategy:
      matrix:
        jdk: [ 17, 21, 24 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Gradle Check
        shell: bash
        run: ./gradlew check --info -S --show-version -Ptoolchain.functionalTest.version=${{ matrix.jdk }}

  build-artifact-bundles:
    name: Build Artifact Bundles
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Build Artifact Bundle
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew --init-script ./.github/init.gradle.kts artifactBundle --info -S --show-version

      - name: Upload Artifact Bundle
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "artifact-bundle"
          path: "./build/libs/maven-artifact-bundle.tgz"

  central-upload:
    name: Upload to Central Portal
    needs: build-artifact-bundles
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact Bundle
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: "artifact-bundle"
          path: .

      - id: upload
        name: Upload to Central Portal
        uses: TheMrMilchmann/central-portal-actions/upload-deployment@v0
        with:
          username: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          password: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          bundle: ./maven-artifact-bundle.tgz
          publishing-type: "user-managed"
    outputs:
      deployment-id: ${{ steps.upload.outputs.deployment-id }}

  gpp-release:
    name: Release to Gradle Plugin Portal
    needs: central-upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      # https://github.com/gradle/gradle/issues/1246
      - name: Install Gradle Plugin Portal credentials
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          mkdir -p ~/.gradle
          echo -e "gradle.publish.key=$GRADLE_PUBLISH_KEY\ngradle.publish.secret=$GRADLE_PUBLISH_SECRET" > ~/.gradle/gradle.properties

      - name: Gradle Publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew check publishPlugins --info -S --show-version

  central-release:
    name: Release to Nexus
    needs: [central-upload, gpp-release]
    runs-on: ubuntu-latest
    steps:
      - name: Release to Central Portal
        uses: TheMrMilchmann/central-portal-actions/publish-deployment@v0
        with:
          username: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          password: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          deployment-id: ${{ needs.central-upload.outputs.deployment-id }}