name: Publish
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to publish to
        type: environment


env:
  JDK_VERSION: "19"
  WORKSPACE_ARCHIVE: workspace.tar
  WORKSPACE_ARTIFACT: build-results


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      - name: Gradle Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble -Psnapshot --info -S --show-version
          gradle-home-cache-cleanup: true

      - name: Tar files
        run: tar -cvf ${{ env.WORKSPACE_ARCHIVE }} .

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT }}
          path: ${{ env.WORKSPACE_ARCHIVE }}
          retention-days: 1


  check:
    name: Check
    strategy:
      matrix:
        jdk: [ 8, 11, 17, 19 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT }}
          path: .

      - name: Untar
        run: |
          tar -xvf ${{ env.WORKSPACE_ARCHIVE }}
          rm ${{ env.WORKSPACE_ARCHIVE }}

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      - name: Gradle Check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check -Psnapshot --info -S --show-version -Ptoolchain.functionalTest.version=${{ matrix.jdk }}
          gradle-home-cache-cleanup: true


  create-staging-repo:
    name: Create Staging Repository
    needs: check
    runs-on: ubuntu-latest
    steps:
      - id: create
        uses: TheMrMilchmann/nexus-actions/create-staging-repo@v1
        with:
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging-profile-id: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}
    outputs:
      staging-repository-id: ${{ steps.create.outputs["staging-repository-id"] }}


  nexus-upload:
    name: Upload to Nexus
    needs: create-staging-repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT }}
          path: .

      - name: Untar
        run: |
          tar -xvf ${{ env.WORKSPACE_ARCHIVE }}
          rm ${{ env.WORKSPACE_ARCHIVE }}

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      - name: Gradle Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check publishAllPublicationsToMavenRepository -Prelease --info -S --show-version
          gradle-home-cache-cleanup: true


  close-staging-repository:
    name: Close Staging Repository
    needs: nexus-upload
    runs-on: ubuntu-latest
    steps:
      - uses: TheMrMilchmann/nexus-actions/close-staging-repo@v1
        with:
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          repository-id: ${{ jobs["create-staging-repo"].outputs["staging-repository-id"] }}
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}


  gpp-release:
    name: Release to Gradle Plugin Portal
    needs: close-staging-repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT }}
          path: .

      - name: Untar
        run: |
          tar -xvf ${{ env.WORKSPACE_ARCHIVE }}
          rm ${{ env.WORKSPACE_ARCHIVE }}

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      # https://github.com/gradle/gradle/issues/1246
      - name: Install Gradle Plugin Portal credentials
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          echo -e "gradle.publish.key=$GRADLE_PUBLISH_KEY\ngradle.publish.secret=$GRADLE_PUBLISH_SECRET" > ~/.gradle/gradle.properties

      - name: Gradle Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check publishPlugins -Prelease --info -S --show-version
          gradle-home-cache-cleanup: true


  nexus-release:
    name: Release to Nexus
    needs: [close-staging-repository, gpp-release]
    runs-on: ubuntu-latest
    steps:
      - name: Release Staging Repository
        uses: TheMrMilchmann/nexus-actions/release-staging-repo@v1
        with:
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          repository-id: ${{ jobs["create-staging-repo"].outputs["staging-repository-id"] }}
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}


  # So, what's happening here?
  #
  # Basically, restoring the workspace state between jobs is incredibly annoying.
  # We can get reasonable support by using the upload-/download-artifact
  # actions, but they suffer from a severe limitation:
  # GH Actions has a storage limit and the minimum retention is 24 hours...
  #
  # Since the storage quota is limited, we have to make sure that the artifact
  # is removed. Unfortunately, there is no official way to do this, so we resort
  # to a third party action for now.
  #
  # See also: https://github.com/actions/upload-artifact/issues/290
  cleanup:
    name: Cleanup
    if: ${{ always() }}
    needs: [release-staging-repo, release-gradle-plugin]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: GeekyEggo/delete-artifact@54ab544f12cdb7b71613a16a2b5a37a9ade990af
        with:
          name: ${{ env.WORKSPACE_ARTIFACT }}